package hotel_booking;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.text.DateFormat;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Vector;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rieje
 */
public class room_management_page extends javax.swing.JFrame {

    private static final String username = "root";
    private static final String password = "Hatdog08_";
    private static final String dataConn = "jdbc:mysql://localhost:3306/room_management";
    
    
    Connection sqlConn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    DefaultTableModel tbmodel = new DefaultTableModel();
    int q, i, RoomID, deleteItem;
    public room_management_page() {
        initComponents();
        upDateDB();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void upDateDB() {
    String[] columnNames = {"Room Number", "Room Type", "Bed", "Price", "Status"};
    DefaultTableModel tbModel = new DefaultTableModel();
    tbModel.setColumnIdentifiers(columnNames);
    jTable1.setModel(tbModel); // Link the model to the table

    String sql = "SELECT RoomNum, RoomType, Bed, Price, Status FROM room_management";

    try (Connection sqlConn = DriverManager.getConnection(dataConn, username, password);
         PreparedStatement pst = sqlConn.prepareStatement(sql);
         ResultSet rs = pst.executeQuery()) {

        while (rs.next()) {
            String roomNum = rs.getString("RoomNum");
            String roomType = rs.getString("RoomType");
            String bed = rs.getString("Bed");
            String price = rs.getString("Price");
            String status = rs.getString("Status");

            tbModel.addRow(new Object[]{roomNum, roomType, bed, price, status});
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
    }
}

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jLabel7 = new javax.swing.JLabel();
        txt_status = new javax.swing.JTextField();
        cb_bedtype = new javax.swing.JComboBox<>();
        txt_room_num1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        bt_bookingdets = new javax.swing.JButton();
        bt_roomanagr = new javax.swing.JButton();
        bt_checkout = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        bt_logout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bt_add = new javax.swing.JButton();
        bt_delete = new javax.swing.JButton();
        txt_room_num = new javax.swing.JTextField();
        txt_price = new javax.swing.JTextField();
        cb_roomtype = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cb_status = new javax.swing.JComboBox<>();
        txt_bed = new javax.swing.JTextField();
        btn_update = new javax.swing.JButton();
        cb_roomnum = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        checkbox_addrn = new javax.swing.JCheckBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jLabel7.setText("jLabel7");

        cb_bedtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Bed", "1 Queen size", "2 Queen size", "3 Double size", "2 King and 2 Single size" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1060, 597));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(165, 157, 173));

        bt_bookingdets.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_bookingdets.setForeground(new java.awt.Color(32, 33, 67));
        bt_bookingdets.setText("Booking Details");
        bt_bookingdets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_bookingdetsActionPerformed(evt);
            }
        });

        bt_roomanagr.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_roomanagr.setForeground(new java.awt.Color(32, 33, 67));
        bt_roomanagr.setText("Room Management");
        bt_roomanagr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_roomanagrActionPerformed(evt);
            }
        });

        bt_checkout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_checkout.setForeground(new java.awt.Color(32, 33, 67));
        bt_checkout.setText("Sales Report");
        bt_checkout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_checkoutActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255, 80));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel_booking/logo 120.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 110));

        bt_logout.setText("Log out");
        bt_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(bt_logout))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt_checkout, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_roomanagr, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_bookingdets, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(bt_bookingdets, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(bt_roomanagr, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(bt_checkout, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_logout)
                .addGap(101, 101, 101))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 631));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Room Number:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 336, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Room Type:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 406, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Bed:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 456, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Price:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 505, -1, -1));

        bt_add.setBackground(new java.awt.Color(204, 255, 204));
        bt_add.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_add.setText("Add");
        bt_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_addActionPerformed(evt);
            }
        });
        jPanel1.add(bt_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(796, 538, 60, -1));

        bt_delete.setBackground(new java.awt.Color(255, 204, 204));
        bt_delete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_delete.setText("Delete");
        bt_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_deleteActionPerformed(evt);
            }
        });
        jPanel1.add(bt_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(953, 538, -1, -1));

        txt_room_num.setEnabled(false);
        txt_room_num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_room_numActionPerformed(evt);
            }
        });
        jPanel1.add(txt_room_num, new org.netbeans.lib.awtextra.AbsoluteConstraints(791, 332, 137, 31));
        jPanel1.add(txt_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 501, 111, 31));

        cb_roomtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Room", "Single Room", "Double Room", "Triple Room", "Quad Room", " " }));
        cb_roomtype.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cb_roomtypeMouseClicked(evt);
            }
        });
        cb_roomtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_roomtypeActionPerformed(evt);
            }
        });
        jPanel1.add(cb_roomtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 401, 272, 33));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Room Management");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(583, 29, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Status:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 456, -1, -1));

        cb_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Available", "Unavailable", " " }));
        cb_status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_statusActionPerformed(evt);
            }
        });
        jPanel1.add(cb_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(563, 456, -1, -1));
        jPanel1.add(txt_bed, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 452, 140, 31));

        btn_update.setBackground(new java.awt.Color(255, 255, 204));
        btn_update.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        jPanel1.add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(868, 538, -1, -1));

        cb_roomnum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Room Number", "R01", "R02", "R03", "R04", "R05", "R06", "R07", "R08", "R09", "R10", "R11", "R12", "R13", "R14", "R15", "R16", "R17", "R18", "R19", "R20" }));
        jPanel1.add(cb_roomnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 336, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Additional Room Number:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(602, 336, -1, -1));

        checkbox_addrn.setText("Add Other Room Number");
        checkbox_addrn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbox_addrnActionPerformed(evt);
            }
        });
        jPanel1.add(checkbox_addrn, new org.netbeans.lib.awtextra.AbsoluteConstraints(602, 369, -1, -1));

        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable1);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 740, 250));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 597, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_addActionPerformed
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            sqlConn = DriverManager.getConnection(dataConn, username, password);
            pst = sqlConn.prepareStatement("insert into room_management(RoomNum, RoomType, Bed, Price, Status)values(?, ?, ?, ?, ?)");
            PreparedStatement checkExist = sqlConn.prepareStatement(
            "SELECT COUNT(*) FROM room_management WHERE RoomNum = ?");
            
            String roomNumber = txt_room_num.getText();
            
            if (checkbox_addrn.isSelected()) {
                if (roomNumber.startsWith("R") && roomNumber.length() > 1) {
                    try {
                        int number = Integer.parseInt(roomNumber.substring(1));
                        if (number >= 21 && number <= 30) {
                            // Duplicate check
                            checkExist.setString(1, roomNumber);
                            ResultSet rs = checkExist.executeQuery();
                            if (rs.next() && rs.getInt(1) > 0) {
                                JOptionPane.showMessageDialog(this, "Room number already exists in the database.");
                                return;
                            }

                            pst.setString(1, roomNumber);
                        } else {
                            JOptionPane.showMessageDialog(this, "Additional room number must be between R21 and R30.");
                            return;
                        }
                    } catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(this, "Invalid number format in room code!");
                        return;
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Invalid room format! Must start with 'R'.");
                    return;
                }
            } else {
                // Get selected room from combo box
                String selectedRoom = cb_roomnum.getSelectedItem().toString();

                // Duplicate check
                checkExist.setString(1, selectedRoom);
                rs = checkExist.executeQuery();
                if (rs.next() && rs.getInt(1) > 0) {
                    JOptionPane.showMessageDialog(this, "Room number already exists in the database.");
                    return;
                }

                pst.setString(1, selectedRoom);
            }
            
            
            
            pst.setString(2, cb_roomtype.getSelectedItem().toString());
            pst.setString(3, txt_bed.getText());
            pst.setInt(4, Integer.parseInt(txt_price.getText()));
            pst.setString(5, cb_status.getSelectedItem().toString());
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Added");
            upDateDB();
        }
        catch (ClassNotFoundException ex){
            java.util.logging.Logger.getLogger(room_management_page.class.getName()).log(java.util.logging.Level.SEVERE, null,ex);
        }catch (SQLException ex){
            java.util.logging.Logger.getLogger(room_management_page.class.getName()).log(java.util.logging.Level.SEVERE, null,ex);
        }
    }//GEN-LAST:event_bt_addActionPerformed

    private void bt_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_logoutActionPerformed
      JOptionPane.showMessageDialog(this, "Logout Succesfully!");
      home_page n=new home_page();
      n.setVisible(true);
      this.setVisible(false);
    }//GEN-LAST:event_bt_logoutActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        admin_home n=new admin_home();
        n.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void bt_checkoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_checkoutActionPerformed
        sales_report n=new sales_report();
        n.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bt_checkoutActionPerformed

    private void bt_roomanagrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_roomanagrActionPerformed
        room_management_page n=new room_management_page();
        n.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bt_roomanagrActionPerformed

    private void bt_bookingdetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_bookingdetsActionPerformed
        booking_details_page n=new booking_details_page();
        n.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bt_bookingdetsActionPerformed

    private void cb_roomtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_roomtypeActionPerformed
        switch (cb_roomtype.getSelectedIndex()) {
            case 1:
                txt_bed.setText("1 Queen Size");
                txt_price.setText(Integer.toString(2999));
                break;
            case 2:
                txt_bed.setText("2 Queen Size");
                txt_price.setText(Integer.toString(9599));
                break;
            case 3:
                txt_bed.setText("1 King, 2 Queen Size");
                txt_price.setText(Integer.toString(15600));
                break;
            case 4:
                txt_bed.setText("2 King, 2 Queen Size");
                txt_price.setText(Integer.toString(20000));
                break;
            default:
                break;
        }
    }//GEN-LAST:event_cb_roomtypeActionPerformed

    private void cb_roomtypeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb_roomtypeMouseClicked

    }//GEN-LAST:event_cb_roomtypeMouseClicked

    private void bt_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_deleteActionPerformed
        DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
        int SelectedRows = jTable1.getSelectedRow();
        
        try{
            String RoomNum = RecordTable.getValueAt(SelectedRows, 0).toString();

            
            deleteItem = JOptionPane.showConfirmDialog(null, "Do you want to delete the item?", "Warning", JOptionPane.YES_NO_OPTION);
            
            if (deleteItem==JOptionPane.YES_OPTION){
                Class.forName("com.mysql.cj.jdbc.Driver");
                sqlConn = DriverManager.getConnection(dataConn, username, password);
                pst = sqlConn.prepareStatement("delete from room_management where roomnum = ?");

                pst.setString(1, RoomNum);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Room Record Deleted");
                upDateDB();
   
                txt_room_num.setText("");
                cb_roomtype.setSelectedItem(0);
                txt_bed.setText("");
                txt_price.setText("");
                cb_status.setSelectedItem(0);  
            }
        }
        catch (ClassNotFoundException ex){
            java.util.logging.Logger.getLogger(room_management_page.class.getName()).log(java.util.logging.Level.SEVERE, null,ex);
        } catch (SQLException ex){
            System.err.println(ex);
        }
    }//GEN-LAST:event_bt_deleteActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
        int SelectedRows = jTable1.getSelectedRow();
        
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            sqlConn = DriverManager.getConnection(dataConn, username, password);
            pst = sqlConn.prepareStatement("update room_management set RoomNumber=?, RoomType=?, Bed=?, Price=?, Status=? where RoomID =? ");
            
                pst.setString(1, txt_room_num.getText());
                pst.setString(1, cb_roomnum.getSelectedItem().toString());
                pst.setString(2, cb_roomtype.getSelectedItem().toString());
                pst.setString(3, txt_bed.getText());
                pst.setInt(4, Integer.parseInt(txt_price.getText()));
                pst.setString(5, cb_status.getSelectedItem().toString());
                pst.setInt(6, Integer.parseInt(RecordTable.getValueAt(SelectedRows, 0).toString()));

                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Record Updated");
                upDateDB();
        }
        catch (ClassNotFoundException ex){
            java.util.logging.Logger.getLogger(room_management_page.class.getName()).log(java.util.logging.Level.SEVERE, null,ex);
        }catch (SQLException ex){
            java.util.logging.Logger.getLogger(room_management_page.class.getName()).log(java.util.logging.Level.SEVERE, null,ex);
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void cb_statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_statusActionPerformed

    private void checkbox_addrnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkbox_addrnActionPerformed
        
        if(checkbox_addrn.isSelected()){
            cb_roomnum.setEnabled(false);
            txt_room_num.setEnabled(true);
        }else{
            cb_roomnum.setEnabled(true);
            txt_room_num.setEnabled(false);
        }
    }//GEN-LAST:event_checkbox_addrnActionPerformed

    private void txt_room_numActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_room_numActionPerformed
    }//GEN-LAST:event_txt_room_numActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        DefaultTableModel RecordTable = (DefaultTableModel) jTable1.getModel();
        int SelectedRows = jTable1.getSelectedRow();

        if (SelectedRows >= 0) {
            String roomNum = RecordTable.getValueAt(SelectedRows, 0).toString();

            if (roomNum.matches("R(0[1-9]|1[0-9]|20)")) {
                cb_roomnum.setSelectedItem(roomNum);
            } else {
                txt_room_num.setText(roomNum);
            }

            cb_roomtype.setSelectedItem(RecordTable.getValueAt(SelectedRows, 1).toString());
            txt_bed.setText(RecordTable.getValueAt(SelectedRows, 2).toString());
            txt_price.setText(RecordTable.getValueAt(SelectedRows, 3).toString());
            cb_status.setSelectedItem(RecordTable.getValueAt(SelectedRows, 4).toString());

            // Only clear the table after processing the selected row (if necessary)
           
        } else {
            System.out.println("No row selected.");
        }
    }//GEN-LAST:event_jTable1MouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(room_management_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(room_management_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(room_management_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(room_management_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new room_management_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_add;
    private javax.swing.JButton bt_bookingdets;
    private javax.swing.JButton bt_checkout;
    private javax.swing.JButton bt_delete;
    private javax.swing.JButton bt_logout;
    private javax.swing.JButton bt_roomanagr;
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox<String> cb_bedtype;
    private javax.swing.JComboBox<String> cb_roomnum;
    private javax.swing.JComboBox<String> cb_roomtype;
    private javax.swing.JComboBox<String> cb_status;
    private javax.swing.JCheckBox checkbox_addrn;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txt_bed;
    private javax.swing.JTextField txt_price;
    private javax.swing.JTextField txt_room_num;
    private javax.swing.JTextField txt_room_num1;
    private javax.swing.JTextField txt_status;
    // End of variables declaration//GEN-END:variables
}
