/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotel_booking;

import java.sql.*;
import java.time.LocalDate;
import java.time.Period;
import javax.swing.JOptionPane;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;

/**
 *
 * @author rieje
 */
public class signup_page extends javax.swing.JFrame {
    Connection con= javaconnect.connectdb();
    PreparedStatement ps=null;
    ResultSet rs=null;
    /**
     * Creates new form signup_page
     */
    public signup_page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField30 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        txt_user = new javax.swing.JTextField();
        txt_bday = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        txt_fn = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        btn_next = new javax.swing.JButton();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        txt_ln = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        txt_cpass = new javax.swing.JPasswordField();
        txt_pass = new javax.swing.JPasswordField();
        jLabel45 = new javax.swing.JLabel();
        txt_cn = new javax.swing.JTextField();
        cb_agree = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel43.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel43.setText("First name:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1060, 597));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(java.awt.SystemColor.controlHighlight);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255, 200));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel36.setFont(new java.awt.Font("Nirmala Text", 1, 24)); // NOI18N
        jLabel36.setText("Sign up");
        jPanel7.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 24, 109, -1));

        jLabel37.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel37.setText("Username:");
        jPanel7.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        jLabel38.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel38.setText("Birthday:");
        jPanel7.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        jLabel39.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel39.setText("Email:");
        jPanel7.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        txt_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_userActionPerformed(evt);
            }
        });
        jPanel7.add(txt_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 340, 25));

        txt_bday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_bdayActionPerformed(evt);
            }
        });
        jPanel7.add(txt_bday, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 340, 25));

        jButton6.setText("Confirm");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(554, 346, -1, -1));
        jPanel7.add(txt_fn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 160, 25));

        jLabel42.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel42.setText("First name:");
        jPanel7.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });
        jPanel7.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 340, 25));

        btn_next.setText("Confirm");
        btn_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nextActionPerformed(evt);
            }
        });
        jPanel7.add(btn_next, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 480, -1, -1));

        jLabel40.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel40.setText("Password:");
        jPanel7.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, -1, -1));

        jLabel41.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel41.setText("Last name:");
        jPanel7.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, -1, -1));

        txt_ln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_lnActionPerformed(evt);
            }
        });
        jPanel7.add(txt_ln, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 160, 25));

        jLabel44.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel44.setText("Confirm Password:");
        jPanel7.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, -1, -1));
        jPanel7.add(txt_cpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 340, 30));
        jPanel7.add(txt_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 340, 30));

        jLabel45.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel45.setText("Contact Number:");
        jPanel7.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));

        txt_cn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cnActionPerformed(evt);
            }
        });
        jPanel7.add(txt_cn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 340, 25));

        cb_agree.setText("I agree with the ");
        cb_agree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_agreeActionPerformed(evt);
            }
        });
        jPanel7.add(cb_agree, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, -1, -1));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 500, 530));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0, 80));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel_booking/logo 120.png"))); // NOI18N
        jLabel4.setText("jLabel2");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 110));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 110));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel_booking/hotelview.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 690));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1110, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        home_page n=new home_page();
        n.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        booking_page n=new booking_page();
        n.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void txt_bdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_bdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_bdayActionPerformed

    private void btn_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nextActionPerformed
        if (con != null) {
    if (txt_fn.getText().trim().isEmpty() || txt_ln.getText().trim().isEmpty() ||
        txt_user.getText().trim().isEmpty() || txt_email.getText().trim().isEmpty() ||
        txt_bday.getText().trim().isEmpty() || txt_cn.getText().trim().isEmpty() ||
        txt_pass.getText().trim().isEmpty() || txt_cpass.getText().trim().isEmpty()) {

        JOptionPane.showMessageDialog(this, "Please fill in all required fields.", "Input Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (!cb_agree.isSelected()) {
        JOptionPane.showMessageDialog(this, "Please read and accept our terms and conditions!", "Input Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    String email = txt_email.getText().trim();
    String emailRegex = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$";
    if (!email.matches(emailRegex)) {
        JOptionPane.showMessageDialog(this, "Please enter a valid email address.", "Input Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        String checkUserSQL = "SELECT * FROM SIGNUP WHERE firstname = ? AND lastname = ? AND username = ? AND email = ?";
        ps = con.prepareStatement(checkUserSQL);
        ps.setString(1, txt_fn.getText().trim());
        ps.setString(2, txt_ln.getText().trim());
        ps.setString(3, txt_user.getText().trim());
        ps.setString(4, txt_email.getText().trim());

        ResultSet rs = ps.executeQuery();
        if (rs.next()) {
            JOptionPane.showMessageDialog(this, "User already exists!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        java.sql.Date bday;
        try {
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("MM-dd-yyyy");
            LocalDate birthDate = LocalDate.parse(txt_bday.getText().trim(), formatter);
            LocalDate today = LocalDate.now();
            int age = Period.between(birthDate, today).getYears();

            if (age < 18) {
                JOptionPane.showMessageDialog(this, "You must be at least 18 years old to sign up.", "Age Restriction", JOptionPane.ERROR_MESSAGE);
                return;
            }

            bday = java.sql.Date.valueOf(birthDate);

        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(null, "Invalid birthday format. Use MM-DD-YYYY", "Input Error!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            String contactStr = txt_cn.getText().trim();
            if (!contactStr.matches("\\d{11}")) {
                JOptionPane.showMessageDialog(null, "Contact number must be exactly 11 digits.", "Input Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Contact number must be digits only.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String pass = txt_pass.getText();
        String conpass = txt_cpass.getText();
        if (!pass.equals(conpass)) {
            JOptionPane.showMessageDialog(null, "Password do not match!", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String insertSQL = "INSERT INTO SIGNUP (firstname, lastname, username, email, birthday, contactnum, password) VALUES (?, ?, ?, ?, ?, ?, ?)";
        PreparedStatement insertPs = con.prepareStatement(insertSQL);
        insertPs.setString(1, txt_fn.getText().trim());
        insertPs.setString(2, txt_ln.getText().trim());
        insertPs.setString(3, txt_user.getText().trim());
        insertPs.setString(4, txt_email.getText().trim());
        insertPs.setDate(5, bday);
        insertPs.setString(6, txt_cn.getText().trim());
        insertPs.setString(7, pass);

        int insertedRows = insertPs.executeUpdate();
        if (insertedRows > 0) {
            JOptionPane.showMessageDialog(this, "Sign Up Successful!", "Success", JOptionPane.INFORMATION_MESSAGE);
            Current.loggedInUsername = txt_user.getText().trim();
            String check_in = BookingData.checkIn;
            String check_out = BookingData.checkOut;

            if (check_in == null || check_in.trim().isEmpty()) {
                Registration_page book = new Registration_page();
                book.setVisible(true);
                this.setVisible(false);
            } else {
                loggedin_home_page loginhp = new loggedin_home_page();
                loginhp.setVisible(true);
                this.setVisible(false);
            }

        } else {
            JOptionPane.showMessageDialog(this, "Error during sign-up.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    } catch (SQLException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Database Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }

} else {
    JOptionPane.showMessageDialog(this, "Failed to connect to database", "Connection Error", JOptionPane.ERROR_MESSAGE);
}

    }//GEN-LAST:event_btn_nextActionPerformed

    private void txt_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_userActionPerformed

    private void txt_lnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_lnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_lnActionPerformed

    private void txt_cnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cnActionPerformed

    private void cb_agreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_agreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_agreeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_next;
    private javax.swing.JCheckBox cb_agree;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField txt_bday;
    private javax.swing.JTextField txt_cn;
    private javax.swing.JPasswordField txt_cpass;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_fn;
    private javax.swing.JTextField txt_ln;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JTextField txt_user;
    // End of variables declaration//GEN-END:variables
}
